"use client";

import { GridRowModesModel } from "@mui/x-data-grid";
import { useEffect, useState } from "react";
import { Box, Chip, Typography } from "@mui/material";
import dayjs from "dayjs";
import DraftReceiptGrid from "./DraftReceiptsGrid";

// NOTE: PreviousReceiptsGrid is imported in the original but not used in the returned JSX.
// Stub retained here so the import resolves once the sibling file is converted.
// import PreviousReceiptsGrid from "./PreviousReceiptsGrid";

// NOTE: GroupByOption / GroupBySelect, PrintButton, MyDialog, SearchField,
// GridSlotProps, GridToolbarContainer, and AdvancedSearchShippingRequests are
// referenced in the PDF source but are not consumed in the rendered JSX.
// They have been omitted to avoid unused-import lint errors.
// Restore them when toolbar / dialog functionality is wired up.

interface DraftReceiptsControllerProps {
  data: any[]; // TODO: improve typing — replace with the actual row interface
}

// NOTE: DraftReceiptsGrid is not yet converted. A minimal stub is provided below
// so this file compiles immediately. Remove the stub once DraftReceiptsGrid.tsx lands.

export default function DraftReceiptsController(
  props: DraftReceiptsControllerProps
) {
  const [rowModesModel, setRowModesModel] = useState<GridRowModesModel>({});
  const [rows, setRows] = useState(props.data ?? []);
  // groupBy / setGroupBy retained from source; unused in current JSX.
  const [groupBy, setGroupBy] = useState("");

  // groupByOptions retained from source for future toolbar wiring.
  const groupByOptions = [
    { value: "generatedBy", label: "Generated By" },
    { value: "logType", label: "Log Type" },
    { value: "son", label: "SON" },
  ];

  useEffect(() => {
    setRows(props.data);
  }, [props.data]);

  const cols = [
    { field: "id" },
    {
      field: "son",
      headerName: "SON",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 100,
    },
    {
      field: "ponum",
      headerName: "PO#",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "ref_no",
      headerName: "Reference No",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 300,
    },
    {
      field: "receiveddate",
      headerName: "Receipt Date",
      flex: 1,
      headerClassName: "col-header",
      type: "date",
      valueGetter: (val: unknown) => (val ? dayjs(val as string) : null),
      valueFormatter: (val: unknown) =>
        val ? (val as ReturnType<typeof dayjs>).format("DD MMM YYYY") : null,
      minWidth: 100,
    },
    {
      field: "receivedtime",
      headerName: "Time",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 100,
    },
    {
      field: "lilist",
      headerName: "Line #",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "pieces",
      headerName: "Pieces",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "route",
      headerName: "Route",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "receiver",
      headerName: "Receiver",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "contains_assets",
      headerName: "Contains Assets?",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "boxlist",
      headerName: "Box Numbers",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
  ];

  function CustomFooter() {
    return (
      <Box sx={{ display: "flex" }}>
        <Typography
          variant="h5"
          color={"#23404f"}
          fontWeight={"700 !important"}
          margin={"0 2rem"}
        >
          {"Legend: "}
          <Chip
            label="Discrepant"
            sx={{
              backgroundColor: "#A5D8F6",
              fontSize: "1.6rem",
              margin: "0 1rem",
            }}
          />
        </Typography>
      </Box>
    );
  }

  return (
    <Box
      maxHeight={"65vh"}
      overflow={"auto"}
      margin={"0 1rem !important"}
      className="simpleGrid"
    >
      <Box className="simpleGrid__headerBox">
        <h1>Draft Receipts</h1>
      </Box>
      <DraftReceiptGrid
        rowsData={rows}
        cols={cols}
        rowModesModel={rowModesModel}
        setRowModesModel={setRowModesModel}
        setRows={setRows}
      />
      <CustomFooter />
    </Box>
  );
}
