"use client";

import { GridRowModesModel } from "@mui/x-data-grid";
// NOTE: GridSlotProps and GridToolbarContainer are imported in the PDF source but not referenced
// in the JSX of this file. They are retained here as comments for completeness.
// import { GridSlotProps, GridToolbarContainer } from "@mui/x-data-grid";
import React, { useEffect, useState } from "react";
import {
  Box,
  Chip,
  IconButton,
  Tooltip,
  Typography,
} from "@mui/material";
// NOTE: Button is imported in the PDF source but not referenced in the JSX of this file.
// import { Button } from "@mui/material";
import { Help } from "@mui/icons-material";
import dayjs from "dayjs";

// NOTE: HoverHint, LightTooltip, MyDialog, SearchField are not yet exported from
// CustomComponents.tsx. Inline stubs provided below — replace once real implementations land.
// NOTE: GroupBySelect / GroupByOption are not yet present in @/components/toolbar/GroupBySelect.
// Inline stubs provided below — replace once that file is converted from its PDF.
// NOTE: PrintButton is not yet present in @/components/toolbar/PrintButton.
// NOTE: AdvancedSearchShippingRequests is not yet present in ../viewshippingrequests/.
// NOTE: PreviousReceiptsGrid is a sibling component to be converted from PreviousReceiptsGrid.pdf.

import PreviousReceiptsGrid from "./PreviousReceiptsGrid";

// ---------------------------------------------------------------------------
// Temporary inline stubs — replace with real imports once companion files exist
// ---------------------------------------------------------------------------

interface LightTooltipProps {
  title: React.ReactNode;
  sx?: object;
  children: React.ReactElement;
}

function LightTooltip({ title, children }: LightTooltipProps) {
  // TODO: replace stub with real LightTooltip from @/components/CustomComponents
  return <Tooltip title={title}>{children}</Tooltip>;
}

interface GroupByOption {
  value: string;
  label: string;
}

// TODO: replace stub with real GroupBySelect from @/components/toolbar/GroupBySelect
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function GroupBySelect(_props: {
  groupBy: string;
  setGroupBy: React.Dispatch<React.SetStateAction<string>>;
  options: GroupByOption[];
}) {
  return null;
}

// TODO: replace stub with real PrintButton from @/components/toolbar/PrintButton
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function PrintButton() {
  return null;
}

// TODO: replace stub with real AdvancedSearchShippingRequests from
// ../viewshippingrequests/AdvancedSearchShippingRequests
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function AdvancedSearchShippingRequests() {
  return null;
}

// TODO: replace stub with real PreviousReceiptsGrid converted from PreviousReceiptsGrid.pdf
// interface PreviousReceiptsGridProps {
//   rowsData: unknown[];
//   cols: unknown[];
//   rowModesModel: GridRowModesModel;
//   setRowModesModel: React.Dispatch<React.SetStateAction<GridRowModesModel>>;
//   setRows: React.Dispatch<React.SetStateAction<unknown[]>>;
// }

// function PreviousReceiptsGrid(_props: PreviousReceiptsGridProps) {
//   return null;
// }

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function PreviousReceiptsController(props: { data: unknown[]; type?: string | null }) {
  const [rowModesModel, setRowModesModel] = useState<GridRowModesModel>({});
  const [rows, setRows] = useState(props.data ?? []);
  // groupBy / groupByOptions / GroupBySelect are wired up in the PDF source but not rendered in
  // the visible JSX. Prefixed with _ to satisfy no-unused-vars until the toolbar is wired in.
  const [_groupBy, _setGroupBy] = useState("");

  const _groupByOptions: GroupByOption[] = [
    { value: "generatedBy", label: "Generated By" },
    { value: "logType", label: "Log Type" },
    { value: "son", label: "SON" },
  ];

  useEffect(() => {
    setRows(props.data);
  }, [props.data]);

  const cols = [
    { field: "id" },
    {
      field: "son",
      headerName: "SON",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 100,
    },
    {
      field: "ponum",
      headerName: "PO#",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "ref_no",
      headerName: "Reference No",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 300,
    },
    {
      field: "receiveddate",
      headerName: "Receipt Date",
      flex: 1,
      headerClassName: "col-header",
      type: "date",
      valueGetter: (val: unknown) => (val ? dayjs(val as string) : null),
      valueFormatter: (val: unknown) =>
        val
          ? (val as { format: (fmt: string) => string }).format("DD MMM YYYY")
          : null,
      minWidth: 100,
    },
    {
      field: "receivedtime",
      headerName: "Time",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 100,
    },
    {
      field: "lilist",
      headerName: "Line #",
      flex: 1,
      headerClassName: "col-header",
      valueFormatter: (val: unknown) =>
        !val ? "No Line Item Receiving" : val,
      minWidth: 150,
    },
    {
      field: "pieces",
      headerName: "Pieces",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "route",
      headerName: "Route",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "receiver",
      headerName: "Receiver",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "contains_assets",
      headerName: "Contains Assets?",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
    {
      field: "boxlist",
      headerName: "Box Numbers",
      flex: 1,
      headerClassName: "col-header",
      minWidth: 150,
    },
  ];

  function CustomFooter() {
    return (
      <Box sx={{ display: "flex" }}>
        <Typography
          variant="h5"
          color={"#23404f"}
          fontWeight={"700 !important"}
          margin={"0 2rem"}
        >
          {"Legend: "}
          <Chip
            label="Discrepant"
            sx={{
              backgroundColor: "#A5D8F6",
              fontSize: "1.6rem",
              margin: "0 1rem",
            }}
          />
        </Typography>
      </Box>
    );
  }

  return (
    <Box
      maxHeight={"65vh"}
      overflow={"auto"}
      margin={"0 1rem !important"}
      className="simpleGrid"
    >
      <Box className="simpleGrid__headerBox">
        <span style={{ display: "flex" }}>
          <h1>Previous Receipts</h1>
          <LightTooltip
            title={
              <React.Fragment>
                <b>{"Instructions on making adjustments:"}</b>
                <br />
                <br />
                <b>{"1."}</b>{" "}
                {
                  "If a user did not receive enough quantity (underage) of a line item, then a new receiving should be done; and"
                }
                <br />
                <br />
                <b>{"2."}</b>{" "}
                {
                  "If a user received too much of a line item (overage), then a return should be done in Previous Receipts."
                }
              </React.Fragment>
            }
            sx={{
              "& .MuiTooltip-popper": {
                fontSize: "24px !important",
              },
            }}
          >
            <IconButton
              sx={{
                "& .MuiSvgIcon-root": {
                  fontSize: "32px",
                },
                margin: "1rem",
                alignItems: "end",
              }}
            >
              <Help />
            </IconButton>
          </LightTooltip>
          {/* <HoverHint hintMessage={helpMessage} /> */}
        </span>
      </Box>
      <PreviousReceiptsGrid
        rowsData={rows}
        cols={cols}
        rowModesModel={rowModesModel}
        setRowModesModel={setRowModesModel}
        setRows={setRows}
        onRowDoubleClick={(params: any) => {
          const row = params.row;
          window.open(
            `/createreceivingform?recId=${row.receivingid ?? row.id}&son=${row.son}&poNumber=${row.ponum ?? ""}&type=${props.type ?? ""}`,
          );
        }}
      />
      <CustomFooter />
    </Box>
  );
}
